# Generated by Django 4.2 on 2023-04-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bestseller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('photo', models.ImageField(blank=True, upload_to='img')),
                ('type', models.CharField(blank=True, max_length=255)),
                ('country', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255)),
                ('composition', models.CharField(blank=True, max_length=255)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(choices=[('Multi', 'Multi'), ('Spring', 'Весна'), ('Summer', 'Лето'), ('Autumn', 'Осень'), ('Winter', 'Зима')], default='Multi', max_length=255)),
            ],
        ),
    ]
